<a href="https://colab.research.google.com/github/pravin7353/Machinelearning/blob/main/Real_World_Data_Breast_cancer_prediction_using_SVM_CLASSIFIER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
from sklearn.datasets import load_breast_cancer

In [ ]:
data = load_breast_cancer()

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
df = pd.DataFrame(np.c_[data.data, data.target], columns=[list(data.feature_names) + ['target']])

In [ ]:
df

mean radius mean texture  ... worst fractal dimension target
0         17.99        10.38  ...                 0.11890    0.0
1         20.57        17.77  ...                 0.08902    0.0
2         19.69        21.25  ...                 0.08758    0.0
3         11.42        20.38  ...                 0.17300    0.0
4         20.29        14.34  ...                 0.07678    0.0
..          ...          ...  ...                     ...    ...
564       21.56        22.39  ...                 0.07115    0.0
565       20.13        28.25  ...                 0.06637    0.0
566       16.60        28.08  ...                 0.07820    0.0
567       20.60        29.33  ...                 0.12400    0.0
568        7.76        24.54  ...                 0.07039    1.0

[569 rows x 31 columns]

## Data Split

In [ ]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [ ]:
X

mean radius mean texture  ... worst symmetry worst fractal dimension
0         17.99        10.38  ...         0.4601                 0.11890
1         20.57        17.77  ...         0.2750                 0.08902
2         19.69        21.25  ...         0.3613                 0.08758
3         11.42        20.38  ...         0.6638                 0.17300
4         20.29        14.34  ...         0.2364                 0.07678
..          ...          ...  ...            ...                     ...
564       21.56        22.39  ...         0.2060                 0.07115
565       20.13        28.25  ...         0.2572                 0.06637
566       16.60        28.08  ...         0.2218                 0.07820
567       20.60        29.33  ...         0.4087                 0.12400
568        7.76        24.54  ...         0.2871                 0.07039

[569 rows x 30 columns]

In [ ]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: (target,), Length: 569, dtype: float64

## Train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
sc.transform_sc = (X_test)

## SUPPORT VECTORM MACHINE FOR CLASSIFICATION

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_rgf = SVC()
svc_rgf.fit(X_train, y_train)
svc_rgf.score(X_test, y_test)

0.9473684210526315

In [ ]:
svc_linear = SVC(kernel='linear')
svc_linear.fit(X_train, y_train)
svc_linear.score(X_test, y_test)

0.956140350877193

In [ ]:
svc_poly = SVC(kernel='poly', degree=2)
svc_poly.fit(X_train, y_train)
svc_poly.score(X_test, y_test)

0.9473684210526315

## TESTING CANCER

In [ ]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [ ]:
patient1_df = np.array(patient1)

In [ ]:
patient1_df

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [ ]:
patient1_sc = sc.transform([patient1_df])

In [ ]:
pred = svc_linear.predict(patient1_sc)
pred

array([0.])

In [ ]:
if pred[0] == 0:
  print('patient has cancer')
else:
  print('patient is safe')

patient has cancer
